### ISSUE TITLE
[Framework Stage 2: UI Theme] Add new + update existing colors according to the new framework design

### ISSUE THREAD

**Issue by jayjayjpg** [meroxa/ui-base#20]
## Context

As part of the Framework integration, we should revisit our color palette to feature both the current and the new, dark mode theme colors.

### Technical Todos

- [x] revisit the [Styleguide](https://www.figma.com/file/p8hTfk0Mlfec6vAF8wcJVM/Style-guide) and the [Framework designs](https://www.figma.com/file/MxZFhvdjkRVzS7OolDbuex/Framework-Mid-fi-Prototype?node-id=64%3A3144) and identify colors that are missing for either of the platform experience
- [x] add missing colors where needed
- [x] update existing colors where needed

**Comment by jayjayjpg** [comment]
### Colors for Dark Theme

Design: https://www.figma.com/file/MxZFhvdjkRVzS7OolDbuex/Turbine-Prototype?node-id=240%3A13196

| name | hex |
|--|--|
| white | `#FFFFFF` |
| slate-20 | `#D6D7D9` |
| gray-300 | `#D1D5DB` |
| gray-400 | `#9CA3AF` |
| gray-900 | `#111827` |
| red-500 | `#EF4444` |
| green-600 | `#059669` |
| cyan-400 | `#22D3EE` |
| cyan-500 | `#06B6D4` |

**Comment by ogeyejammy** [comment]
LGTM

**Comment by jayjayjpg** [comment]
We can adjust the color palette even further as follows:

Styleguide: https://www.figma.com/file/p8hTfk0Mlfec6vAF8wcJVM/Style-guide?node-id=865%3A587

| name | hex |
|--|--|
| white | `#FFFFFF` |
| slate-20 | `#D6D7D9` |
| gray-50 | `#f9fafb` |
| gray-300 | `#D1D5DB` |
| ~gray-400~ | ~`#9CA3AF`~ |
| gray-900 | `#111827` |
| red-500 | `#EF4444` |
| green-600 | `#059669` |
| ~cyan-400~ | ~`#22D3EE`~ |
| cyan-500 | `#06B6D4` |
| yellow-400 | `#FBBF24` |
| teal-600 | `#0D9488` |
| teal-900 | `#134E4A` |
| purple-600 | `#9333EA` |
| orange-700 | `#C2410C` |
